### ISSUE TITLE
Slogan: Improper Use of "Abridge"

### ISSUE THREAD

**Issue by jyhi** [UICHCC/HCC-Regulations#4]
Currently our slogans are:

- Abridge You and Technology
- A Bridge Between You and Technology

However, the meaning of **"abridge"** is not accurate:

- _to shorten by omissions while retaining the basic contents_
- _to reduce or lessen in duration, scope, authority, etc.; diminish; **curtail**_ (this is bad)
- _to **deprive**; cut off_ (this is even worse)

(http://www.dictionary.com/browse/abridge)

I believe that we originally want a verb of "bridge". Fortunately, "bridge" itself can be a verb:

- _22. to join by or as if by a bridge_

(http://www.dictionary.com/browse/bridge)

Thus, I propose a change to our slogan, to:

- ~~**Bridge You and Technology**~~
- ~~(Alternative) **A Bridge Between You and Technology**~~
- **~~Bridge~~ Bridging You And Technology**
- (Alternative) **A Bridge Between You And Technology**

~~Also, I propose a "short" form of slogan for future use:~~

- ~~**Bridge.**~~
- ~~**A Bridge.**~~

Request for comments.

**Comment by mchobbylong** [comment]
Agree to change slogans to the new one **Bridge You and Technology**.

The alternative one **A Bridge Between You and Technology** sounds like a kind of definition, but not quite proper for a slogan that usually contains verbs to form a feeling of inspiration.

Have no comments for the short form of slogan. Either accepted or no is fine.

**Comment by billzhonggz** [comment]
Grammar fix: Bridg**ing** you and technology.

**Comment by jyhi** [comment]
> Grammar fix: Bridging you and technology.

Fixed by editing.

Also I changed the order of "technology" and "you", it looks better for me.

**Comment by ecwu** [comment]
Not recommend the short form of the slogan.

**Comment by jyhi** [comment]
> Not recommend the short form of the slogan.

Do you want to remove the short form or change them?

**Comment by ecwu** [comment]
> Do you want to remove the short form or change them?

I feel confused if I only see the short form of the slogan. 

But the new one: `Bridging Technology and You` & `(Alternative) A Bridge Between Technology and You` are great.

**Comment by jyhi** [comment]
@ecwu Then let's drop it.

**Comment by jyhi** [comment]
One more thing. Do you think

    Bridging Technology and You

is better? (words "technology" and "you" are swapped)

**Comment by billzhonggz** [comment]
I think keep 'you' at the front is better.

**Comment by jyhi** [comment]
> I think keep 'you' at the front is better.

Alright, then the final form will be:

- **Bridging You And Technology.**
- **A Bridge Between You And Technology.**

A PR will be assigned later.
