### ISSUE TITLE
UICHCC Information Security Regulations

### ISSUE THREAD

**Issue by ecwu** [UICHCC/HCC-Regulations#9]
In the future development, the number and types of our infrastructure will surely increase. And there will be more and more keys and passwords for managing and accessing those infrastructures

Since UICHCC attach great importance to information security issues. I think we need to start to develop relevant regulations on information security now.

This rule can be used to standardize operations in the future. Also educational.

**Comment by jyhi** [comment]
Some technical ideas (paranoid warning):

- At least Core members should know how to prove themselves on the Internet
  - Applied GnuPG
- At least Infrastructure members should have GnuPG keys for information exchange
- Symmetric keys used should be exchanged and saved using asymmetric keys
  - Symmetric keys should be strong enough
    - Randomly generated, at least 16 characters long, with upper and lower case alphabets, numbers, and special characters
  - If any asymmetric key is leaked, all symmetric keys should change
